name: visualizing_the_top_15_water_consuming_countries_using_a_flutter_column_chart
description: "Syncfusion Flutter Column Chart data label customization."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^27.1.50

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/images/Azerbaijan.png
    - assets/images/Chile.png
    - assets/images/Estonia.png
    - assets/images/Finland.png
    - assets/images/Guyana.png
    - assets/images/Iran.png
    - assets/images/Kazakhstan.png
    - assets/images/Kyrgyzstan.png
    - assets/images/New-Zealand.png
    - assets/images/Suriname.png
    - assets/images/Tajikistan.png
    - assets/images/Timor.png
    - assets/images/Turkmenistan.png
    - assets/images/United-States.png
    - assets/images/Uzbekistan.png

  uses-material-design: true
